version: 1.2
tools:
   - name: valid-tool-name
     subclass: cwl
     primaryDescriptorPath: /tools/Dockstore.cwl
workflows:
   - name: invalid/workflow/name
     subclass: cwl
     primaryDescriptorPath: /workflows/HelloWorld.cwl
